# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='proto',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63\x61lculator.proto\x12\x05proto\"4\n\x12\x43\x61lculationRequest\x12\x0e\n\x06input1\x18\x01 \x01(\x05\x12\x0e\n\x06input2\x18\x02 \x01(\x05\"\"\n\x10\x43\x61lculationReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32I\n\nCalculator\x12;\n\x03\x61\x64\x64\x12\x19.proto.CalculationRequest\x1a\x17.proto.CalculationReply\"\x00\x42*\n\x0fio.CMPE272.Lab2B\x0f\x63\x61lculatorprotoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_CALCULATIONREQUEST = _descriptor.Descriptor(
  name='CalculationRequest',
  full_name='proto.CalculationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input1', full_name='proto.CalculationRequest.input1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input2', full_name='proto.CalculationRequest.input2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=79,
)


_CALCULATIONREPLY = _descriptor.Descriptor(
  name='CalculationReply',
  full_name='proto.CalculationReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='proto.CalculationReply.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['CalculationRequest'] = _CALCULATIONREQUEST
DESCRIPTOR.message_types_by_name['CalculationReply'] = _CALCULATIONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalculationRequest = _reflection.GeneratedProtocolMessageType('CalculationRequest', (_message.Message,), dict(
  DESCRIPTOR = _CALCULATIONREQUEST,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:proto.CalculationRequest)
  ))
_sym_db.RegisterMessage(CalculationRequest)

CalculationReply = _reflection.GeneratedProtocolMessageType('CalculationReply', (_message.Message,), dict(
  DESCRIPTOR = _CALCULATIONREPLY,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:proto.CalculationReply)
  ))
_sym_db.RegisterMessage(CalculationReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\017io.CMPE272.Lab2B\017calculatorprotoP\001\242\002\003HLW'))

_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='proto.Calculator',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=117,
  serialized_end=190,
  methods=[
  _descriptor.MethodDescriptor(
    name='add',
    full_name='proto.Calculator.add',
    index=0,
    containing_service=None,
    input_type=_CALCULATIONREQUEST,
    output_type=_CALCULATIONREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
